import { useState } from 'react';
import { Copy, Mail, Plus, Send, ShieldCheck, Trash2, User } from 'lucide-react';
import { apiClient } from '../../api/client';
import { useCompanyDebounce, useCompanyResource } from '../../hooks/useCompanyResource';
import { CompanyBadge, CompanyCard, CompanyDecision, CompanyDialog, CompanyPagination, CompanyState, CompanyTable, companyDate, companyMoney } from './CompanyUi';
import { useCompanyWorkspace } from './CompanyWorkspace';

export interface CompanyPerson { id: number; firstName?: string; lastName?: string; email: string; designation?: string; companyVerified?: boolean; active?: boolean }
interface CompanyInvitation { id: number; email: string; recipientName?: string; designation?: string; role: string; status: string; autoVerifyBadge: boolean; inviteLink?: string; expiresAt?: string; createdAt: string }
export interface CompanyEmployee { id: number; candidateName: string; candidateEmail: string; employeeCode: string; department?: string; jobTitle: string; status: string; baseSalary?: number; salaryCurrency?: string; createdAt: string; employmentType?: string; terminationStatus?: string; terminationReason?: string; noticePeriodDays?: number }
export interface CompanyReview { id: number; employeeName: string; employeeId: number; reviewPeriod: string; rating: number; ratingCategory: string; feedback?: string; goalsOkrs?: string; reviewerName: string }

export function CompanyInviteDialog({ role, person, onClose, onSuccess }: { role: 'ROLE_HR' | 'ROLE_CANDIDATE'; person?: CompanyPerson; onClose: () => void; onSuccess: () => void }) {
  const [email, setEmail] = useState(person?.email || '');
  const [name, setName] = useState(person ? `${person.firstName || ''} ${person.lastName || ''}`.trim() : '');
  const [designation, setDesignation] = useState('');
  const [autoBadge, setAutoBadge] = useState(true);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <CompanyDialog title={role === 'ROLE_HR' ? 'Invite HR recruiter' : 'Invite candidate'} onClose={() => { if (!busy) onClose(); }}><form onSubmit={async event => {
    event.preventDefault(); setBusy(true); setError('');
    try { await apiClient.post('/admin/company/invitations', { email: email.trim(), recipientName: name.trim(), role, designation: designation.trim(), autoVerifyBadge: autoBadge }); onSuccess(); onClose(); }
    catch (err: any) { setError(err?.response?.data?.message || 'The invitation could not be sent. Please try again.'); } finally { setBusy(false); }
  }}><p>An email invitation will be sent with a recipient-specific onboarding link.</p><label className="cm-field">Email address *<input required type="email" maxLength={255} autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="name@company.com" /></label><label className="cm-field">Full name<input value={name} maxLength={200} onChange={event => setName(event.target.value)} placeholder="Recipient’s name" /></label><label className="cm-field">{role === 'ROLE_HR' ? 'Designation' : 'Proposed job title'}<input value={designation} maxLength={200} onChange={event => setDesignation(event.target.value)} placeholder="Enter a role or title" /></label><label className="cm-check"><input type="checkbox" checked={autoBadge} onChange={event => setAutoBadge(event.target.checked)} />Automatically award the company badge when this invitation is accepted.</label>{error && <p role="alert" className="cm-error-text">{error}</p>}<footer className="cm-actions cm-form-actions"><button type="button" className="cm-button" disabled={busy} onClick={onClose}>Cancel</button><button className="cm-button cm-button-primary" disabled={busy}><Send size={15} />{busy ? 'Sending…' : 'Send invitation'}</button></footer></form></CompanyDialog>;
}

export function CompanyInvitations({ role }: { role: 'ROLE_HR' | 'ROLE_CANDIDATE' }) {
  const resource = useCompanyResource<CompanyInvitation[]>('/admin/company/invitations');
  const [search, setSearch] = useState(''); const [page, setPage] = useState(0);
  const [inviteOpen, setInviteOpen] = useState(false);
  const [decision, setDecision] = useState<{ invitation: CompanyInvitation; action: 'resend' | 'revoke' } | null>(null);
  const [notice, setNotice] = useState('');
  const invitations = (resource.data || []).filter(invite => invite.role === role && `${invite.recipientName} ${invite.email} ${invite.status}`.toLowerCase().includes(search.toLowerCase()));
  const pageCount = Math.ceil(invitations.length / 10); const currentPage = Math.min(page, Math.max(0, pageCount - 1));
  return <CompanyCard title={role === 'ROLE_HR' ? 'Recruiter invitations' : 'Candidate invitations'} description="Track invitation status, copy issued links, or resend an invitation." action={<button className="cm-button cm-button-primary" onClick={() => setInviteOpen(true)}><Plus size={15} /> Invite</button>}>
    <div className="cm-toolbar"><label className="cm-field">Search invitations<input type="search" value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} placeholder="Search name, email or status" /></label><button className="cm-button" onClick={resource.refresh}>Refresh</button></div>
    {notice && <p className="cm-notice" role="status">{notice}</p>}
    {resource.loading || resource.error || !invitations.length ? <CompanyState loading={resource.loading} error={resource.error} empty="No matching invitations" onRetry={resource.refresh} /> : <><CompanyTable label="Company invitations" headings={['Recipient', 'Designation', 'Badge', 'Status / expiry', 'Actions']}>
      {invitations.slice(currentPage * 10, currentPage * 10 + 10).map(invite => <tr key={invite.id}><td><strong>{invite.recipientName || 'Invited member'}</strong><small>{invite.email}</small></td><td>{invite.designation || 'Not specified'}</td><td>{invite.autoVerifyBadge ? 'Automatic' : 'Manual review'}</td><td><CompanyBadge value={invite.status} /><small>{companyDate(invite.expiresAt)}</small></td><td><div className="cm-actions">{invite.inviteLink && invite.status === 'PENDING' && <button className="cm-icon-button" aria-label={`Copy invitation for ${invite.email}`} onClick={async () => { try { await navigator.clipboard.writeText(invite.inviteLink!); setNotice('Invitation link copied. Share it only with the intended recipient.'); } catch { setNotice('Clipboard access was denied. Please try again.'); } }}><Copy size={15} /></button>}{['PENDING', 'EXPIRED'].includes(invite.status) && <button className="cm-icon-button" aria-label={`Resend invitation to ${invite.email}`} onClick={() => setDecision({ invitation: invite, action: 'resend' })}><Mail size={15} /></button>}{invite.status === 'PENDING' && <button className="cm-icon-button" aria-label={`Revoke invitation for ${invite.email}`} onClick={() => setDecision({ invitation: invite, action: 'revoke' })}><Trash2 size={15} /></button>}</div></td></tr>)}
    </CompanyTable><CompanyPagination page={{ currentPage, totalPages: pageCount, totalElements: invitations.length, pageSize: 10 }} onChange={setPage} /></>}
    {inviteOpen && <CompanyInviteDialog role={role} onClose={() => setInviteOpen(false)} onSuccess={() => { resource.refresh(); setNotice('Invitation sent successfully.'); }} />}
    {decision && <CompanyDecision title={decision.action === 'revoke' ? 'Revoke invitation?' : 'Resend invitation?'} description={`${decision.action === 'revoke' ? 'Invalidate the onboarding link for' : 'Send a renewed invitation email to'} ${decision.invitation.email}.`} confirmLabel={decision.action === 'revoke' ? 'Revoke invitation' : 'Resend invitation'} onClose={() => setDecision(null)} onConfirm={async () => { if (decision.action === 'revoke') await apiClient.delete(`/admin/company/invitations/${decision.invitation.id}`); else await apiClient.post(`/admin/company/invitations/${decision.invitation.id}/resend`); resource.refresh(); }} />}
  </CompanyCard>;
}

export function CompanyRecruiters({ approvals = false }: { approvals?: boolean }) {
  const resource = useCompanyResource<CompanyPerson[]>('/admin/company/team/hrs'); const workspace = useCompanyWorkspace();
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState(approvals ? 'PENDING' : 'ALL'); const [page, setPage] = useState(0);
  const [invite, setInvite] = useState(false); const [selected, setSelected] = useState<CompanyPerson | null>(null);
  const people = (resource.data || []).filter(person => `${person.firstName} ${person.lastName} ${person.email} ${person.designation || ''}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'ALL' || (filter === 'VERIFIED' ? person.companyVerified : filter === 'PENDING' ? !person.companyVerified : !person.active)));
  const currentPage = Math.min(page, Math.max(0, Math.ceil(people.length / 10) - 1));
  return <CompanyCard title={approvals ? "Recruiter badge approvals" : "Recruiter roster"} description="Company-affiliated recruiters and their current verification status." action={<button className="cm-button cm-button-primary" onClick={() => setInvite(true)}><Plus size={15} /> Invite recruiter</button>}><div className="cm-toolbar"><label className="cm-field">Search recruiters<input type="search" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} placeholder="Name, email or designation" /></label><label className="cm-field">Status<select value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}><option value="ALL">All recruiters</option><option value="VERIFIED">Verified</option><option value="PENDING">Not verified</option><option value="INACTIVE">Inactive</option></select></label><button className="cm-button" onClick={resource.refresh}>Refresh</button></div>
    {resource.loading || resource.error || !people.length ? <CompanyState loading={resource.loading} error={resource.error} empty="No matching recruiters" onRetry={resource.refresh} /> : <><CompanyTable label="Recruiter roster" headings={['Recruiter', 'Designation', 'Verification', 'Account', 'Action']}>{people.slice(currentPage * 10, currentPage * 10 + 10).map(person => <tr key={person.id}><td><strong>{person.firstName} {person.lastName}</strong><small>{person.email}</small></td><td>{person.designation || 'Not specified'}</td><td><CompanyBadge value={person.companyVerified} /></td><td><CompanyBadge value={person.active ? 'ACTIVE' : 'INACTIVE'} /></td><td><button className="cm-button" onClick={() => setSelected(person)}><ShieldCheck size={14} />{person.companyVerified ? 'Revoke badge' : 'Verify recruiter'}</button></td></tr>)}</CompanyTable><CompanyPagination page={{ currentPage, totalPages: Math.ceil(people.length / 10), totalElements: people.length, pageSize: 10 }} onChange={setPage} /></>}
    {invite && <CompanyInviteDialog role="ROLE_HR" onClose={() => setInvite(false)} onSuccess={resource.refresh} />}
    {selected && <CompanyDecision title={selected.companyVerified ? 'Revoke recruiter badge?' : 'Verify recruiter?'} description={`This changes company verification for ${selected.email} and may affect their access to company workflows.`} confirmLabel={selected.companyVerified ? 'Revoke badge' : 'Verify recruiter'} onClose={() => setSelected(null)} onConfirm={async () => { await apiClient.put(`/admin/company/hrs/${selected.id}/badge`, { verified: !selected.companyVerified }); resource.refresh(); workspace.refresh(); }} />}
  </CompanyCard>;
}

export function CompanyTalent() {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(0);
  const query = useCompanyDebounce(search);
  const resource = useCompanyResource<CompanyPerson[]>(`/admin/company/candidates/pool?search=${encodeURIComponent(query)}&page=${page}&size=12`);
  const [invite, setInvite] = useState<{ role: 'ROLE_HR' | 'ROLE_CANDIDATE'; person?: CompanyPerson } | null>(null);
  return <CompanyCard title="Discover talent" description="Active candidate profiles available through the platform’s existing discovery workflow." action={<button className="cm-button cm-button-primary" onClick={() => setInvite({ role: 'ROLE_CANDIDATE' })}><Plus size={15} /> Invite by email</button>}><div className="cm-toolbar"><label className="cm-field">Search candidates<input type="search" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} placeholder="Search name or email" /></label><button className="cm-button" onClick={resource.refresh}>Refresh</button></div>{resource.loading || resource.error || !resource.data?.length ? <CompanyState loading={resource.loading} error={resource.error} empty="No candidates found" onRetry={resource.refresh} /> : <><div className="cm-candidate-grid">{resource.data.map(person => <article className="cm-person" key={person.id}><span className="cm-avatar"><User size={18} /></span><h3>{person.firstName} {person.lastName}</h3><p>{person.email}</p><div className="cm-actions"><button className="cm-button" onClick={() => setInvite({ role: 'ROLE_HR', person })}>Invite as HR</button><button className="cm-button cm-button-teal" onClick={() => setInvite({ role: 'ROLE_CANDIDATE', person })}>Invite candidate</button></div></article>)}</div><CompanyPagination page={resource.page} onChange={setPage} /></>}{invite && <CompanyInviteDialog {...invite} onClose={() => setInvite(null)} onSuccess={resource.refresh} />}</CompanyCard>;
}

export function CompanyDirectory() {
  const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(0);
  const query = useCompanyDebounce(search);
  const resource = useCompanyResource<CompanyEmployee[]>(`/employees?page=${page}&size=15&status=${status}&search=${encodeURIComponent(query)}`);
  const [employee, setEmployee] = useState<CompanyEmployee | null>(null);
  return <CompanyCard title="Employee directory" description="Browse all company employment records. Filters apply across the full directory."><div className="cm-toolbar"><label className="cm-field">Search employees<input type="search" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} placeholder="Name, email, code or department" /></label><label className="cm-field">Employment status<select value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}><option value="">All employees</option>{['ACTIVE', 'PENDING_VERIFICATION', 'ON_NOTICE', 'REJECTED', 'TERMINATED', 'SUSPENDED'].map(value => <option key={value}>{value}</option>)}</select></label><button className="cm-button" onClick={resource.refresh}>Refresh</button></div>{resource.loading || resource.error || !resource.data?.length ? <CompanyState loading={resource.loading} error={resource.error} empty="No matching employees" onRetry={resource.refresh} /> : <><CompanyTable label="Employee directory" headings={['Employee', 'Department / role', 'Compensation', 'Status', 'Details']}>{resource.data.map(person => <tr key={person.id}><td><strong>{person.candidateName}</strong><small>{person.employeeCode} · {person.candidateEmail}</small></td><td>{person.department || 'Not specified'}<small>{person.jobTitle}</small></td><td>{companyMoney(person.baseSalary, person.salaryCurrency)}</td><td><CompanyBadge value={person.status} /></td><td><button className="cm-button" onClick={() => setEmployee(person)}>View details</button></td></tr>)}</CompanyTable><CompanyPagination page={resource.page} onChange={setPage} /></>}{employee && <CompanyDialog title="Employee details" onClose={() => setEmployee(null)}><dl className="cm-details">{[['Name', employee.candidateName], ['Email', employee.candidateEmail], ['Employee code', employee.employeeCode], ['Department', employee.department], ['Job title', employee.jobTitle], ['Employment type', employee.employmentType], ['Status', employee.status], ['Compensation', companyMoney(employee.baseSalary, employee.salaryCurrency)], ['Record created', companyDate(employee.createdAt)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || 'Not recorded'}</dd></div>)}</dl></CompanyDialog>}</CompanyCard>;
}

export function CompanyReviewDialog({ onClose, onSuccess }: { onClose: () => void; onSuccess: () => void }) {
  const [search, setSearch] = useState(''); const query = useCompanyDebounce(search);
  const employees = useCompanyResource<CompanyEmployee[]>(`/employees?page=0&size=50&search=${encodeURIComponent(query)}`);
  const [employeeId, setEmployeeId] = useState(''); const [period, setPeriod] = useState(`Q${Math.floor(new Date().getMonth() / 3) + 1} ${new Date().getFullYear()}`);
  const [rating, setRating] = useState(''); const [feedback, setFeedback] = useState(''); const [goals, setGoals] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <CompanyDialog title="New performance review" onClose={() => { if (!busy) onClose(); }}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await apiClient.post('/admin/company/performance', { employeeId: Number(employeeId), reviewPeriod: period.trim(), rating: Number(rating), feedback: feedback.trim(), goalsOkrs: goals.trim() }); onSuccess(); onClose(); } catch (err: any) { setError(err?.response?.data?.message || 'Review could not be saved.'); } finally { setBusy(false); } }}>
    <label className="cm-field">Find employee<input type="search" value={search} onChange={e => { setSearch(e.target.value); setEmployeeId(''); }} placeholder="Search the company directory" /></label><label className="cm-field">Employee *<select required value={employeeId} onChange={e => setEmployeeId(e.target.value)} disabled={employees.loading}><option value="">Select employee</option>{employees.data?.map(person => <option value={person.id} key={person.id}>{person.candidateName} · {person.employeeCode}</option>)}</select><small>Search by name to narrow the first 50 results.</small></label>{employees.error && <p role="alert" className="cm-error-text">{employees.error}</p>}
    <div className="cm-grid"><label className="cm-field">Review period *<input required maxLength={50} value={period} onChange={e => setPeriod(e.target.value)} /></label><label className="cm-field">Overall rating (1–5) *<input type="number" required min={1} max={5} step="0.01" value={rating} onChange={e => setRating(e.target.value)} placeholder="Enter rating" /></label></div><label className="cm-field">Feedback<textarea value={feedback} maxLength={5000} onChange={e => setFeedback(e.target.value)} rows={4} placeholder="Record strengths, contributions and growth areas." /></label><label className="cm-field">Goals / OKRs<textarea value={goals} maxLength={5000} onChange={e => setGoals(e.target.value)} rows={3} placeholder="Agreed goals for the next review period." /></label>{error && <p role="alert" className="cm-error-text">{error}</p>}<footer className="cm-actions cm-form-actions"><button className="cm-button" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="cm-button cm-button-primary" disabled={busy || !employeeId}>{busy ? 'Saving…' : 'Save review'}</button></footer>
  </form></CompanyDialog>;
}

export function CompanyReviews() {
  const [page, setPage] = useState(0); const [open, setOpen] = useState(false); const [selected, setSelected] = useState<CompanyReview | null>(null);
  const resource = useCompanyResource<CompanyReview[]>(`/admin/company/performance?page=${page}&size=15`);
  return <CompanyCard title="Performance reviews" description="Recorded ratings and feedback. Reviews remain restricted to your company." action={<button className="cm-button cm-button-primary" onClick={() => setOpen(true)}><Plus size={15} /> New review</button>}>{resource.loading || resource.error || !resource.data?.length ? <CompanyState loading={resource.loading} error={resource.error} empty="No performance reviews yet" onRetry={resource.refresh} /> : <><CompanyTable label="Performance reviews" headings={['Employee', 'Period', 'Rating', 'Category', 'Reviewer', 'Details']}>{resource.data.map(review => <tr key={review.id}><td><strong>{review.employeeName}</strong></td><td>{review.reviewPeriod}</td><td>{review.rating} / 5</td><td><CompanyBadge value={review.ratingCategory} /></td><td>{review.reviewerName}</td><td><button className="cm-button" onClick={() => setSelected(review)}>Read review</button></td></tr>)}</CompanyTable><CompanyPagination page={resource.page} onChange={setPage} /></>}{open && <CompanyReviewDialog onClose={() => setOpen(false)} onSuccess={resource.refresh} />}{selected && <CompanyDialog title={`${selected.employeeName} — review`} onClose={() => setSelected(null)}><p>{selected.reviewPeriod} · {selected.rating} / 5</p><h3>Feedback</h3><p className="cm-prose">{selected.feedback || 'No feedback recorded.'}</p><h3>Goals / OKRs</h3><p className="cm-prose">{selected.goalsOkrs || 'No goals recorded.'}</p></CompanyDialog>}</CompanyCard>;
}
