import React, { useState, useEffect } from 'react';
import { Sparkles, Moon, X, RefreshCw } from 'lucide-react';
import '../css/cosmic-quote.css';

interface CosmicFact {
  id: number;
  category: 'GALAXY' | 'PLANET' | 'EARTH' | 'COSMIC_QUOTE' | 'STAR_PHYSICS';
  badge: string;
  icon: string;
  color: string;
  title: string;
  fact: string;
  authorOrSource?: string;
}

const COSMIC_FACTS: CosmicFact[] = [
  // ── Galaxy Facts ──
  {
    id: 1,
    category: 'GALAXY',
    badge: '🌌 Milky Way Galaxy',
    icon: 'galaxy',
    color: '#A78BFA',
    title: 'Galactic Orbital Velocity',
    fact: 'Our entire Solar System travels at an astonishing speed of 828,000 km/h (514,000 mph) around the supermassive black hole Sagittarius A* at the center of the Milky Way, taking approximately 230 million years to complete one single cosmic orbit.',
    authorOrSource: 'NASA Astrophysics & ESA Gaia Mission'
  },
  {
    id: 2,
    category: 'GALAXY',
    badge: '🌌 Galactic Scale',
    icon: 'galaxy',
    color: '#818CF8',
    title: 'The Observable Horizon',
    fact: 'There are estimated to be over 2 trillion galaxies in the observable universe. If every grain of sand on Earth represented a star, the universe would still contain more stars than all beaches and deserts combined on our planet.',
    authorOrSource: 'Hubble Deep Field Survey'
  },
  {
    id: 3,
    category: 'GALAXY',
    badge: '🌌 Cosmic Collision',
    icon: 'galaxy',
    color: '#C084FC',
    title: 'Milkomeda Future Dance',
    fact: 'In approximately 4.5 billion years, our Milky Way galaxy will collide and merge with the Andromeda galaxy (M31). Because of vast distances between stars, virtually no two stars are expected to directly collide during the merger.',
    authorOrSource: 'Astrophysical Journal'
  },

  // ── Planetary Wonders ──
  {
    id: 4,
    category: 'PLANET',
    badge: '🪐 Planetary Wonder: Saturn',
    icon: 'planet',
    color: '#FBBF24',
    title: 'Saturn\'s Whispering Rings',
    fact: 'Saturn\'s majestic rings span up to 282,000 kilometers across, yet are extraordinarily thin—often only 10 to 30 meters thick. They are composed of billions of individual particles of water ice and cosmic dust ranging from micro-grains to house-sized boulders.',
    authorOrSource: 'Cassini-Huygens Mission'
  },
  {
    id: 5,
    category: 'PLANET',
    badge: '🪐 Planetary Wonder: Jupiter',
    icon: 'planet',
    color: '#F59E0B',
    title: 'The Great Red Shield',
    fact: 'Jupiter\'s Great Red Spot is a colossal anticyclonic storm larger than Earth that has raged for at least 350 years. Jupiter has twice the mass of all other planets in the solar system combined and acts as a cosmic gravitational shield protecting Earth from asteroid strikes.',
    authorOrSource: 'NASA Juno Spacecraft'
  },
  {
    id: 6,
    category: 'PLANET',
    badge: '🪐 Planetary Wonder: Venus',
    icon: 'planet',
    color: '#FB923C',
    title: 'Retrograde Rotation',
    fact: 'A single day on Venus (243 Earth days) is longer than its entire year (225 Earth days). Furthermore, Venus rotates backwards (retrograde) compared to most planets, meaning the Sun rises in the West and sets in the East.',
    authorOrSource: 'Magellan Planetary Survey'
  },
  {
    id: 7,
    category: 'PLANET',
    badge: '🪐 Planetary Wonder: Mars',
    icon: 'planet',
    color: '#EF4444',
    title: 'Olympus Mons — Solar Giant',
    fact: 'Mars is home to Olympus Mons, the largest volcano and planetary shield in our solar system. Standing nearly 22 kilometers (13.6 miles) high, it is roughly three times taller than Mount Everest and covers an area the size of the entire country of France.',
    authorOrSource: 'NASA Mars Reconnaissance Orbiter'
  },
  {
    id: 8,
    category: 'PLANET',
    badge: '🪐 Planetary Wonder: Mercury',
    icon: 'planet',
    color: '#94A3B8',
    title: 'Extreme Thermal Oceans',
    fact: 'Mercury has virtually no atmosphere to trap heat, resulting in the most extreme temperature swings in the solar system: soaring to 430°C (800°F) during the daytime and plummeting to -180°C (-290°F) at night.',
    authorOrSource: 'MESSENGER Mission'
  },

  // ── Earth Wonders ──
  {
    id: 9,
    category: 'EARTH',
    badge: '🌍 Earth Wonder',
    icon: 'earth',
    color: '#34D399',
    title: 'The Pale Blue Dot Magnetosphere',
    fact: 'Earth is protected by a dynamic geodynamo magnetic field generated by churning molten iron in our outer core 3,000 kilometers beneath our feet. This invisible shield deflects lethal solar wind and cosmic rays, making complex life possible.',
    authorOrSource: 'Geophysical Research Letters'
  },
  {
    id: 10,
    category: 'EARTH',
    badge: '🌍 Earth Wonder',
    icon: 'earth',
    color: '#38BDF8',
    title: 'Ancient Water Origins',
    fact: 'More than 70% of Earth\'s surface is covered by liquid water, and scientific isotope analysis reveals that much of the water in our oceans is older than the Sun itself, having originated in interstellar molecular clouds over 4.6 billion years ago.',
    authorOrSource: 'Science Journal / ESA Rosetta'
  },
  {
    id: 11,
    category: 'EARTH',
    badge: '🌍 Earth Wonder',
    icon: 'earth',
    color: '#10B981',
    title: 'The Atmospheric Goldilocks Veil',
    fact: 'Earth\'s atmosphere is roughly 100 kilometers thick to the Kármán Line. Relative to the size of Earth (12,742 km diameter), our breathable atmosphere is thinner than the skin of an apple, perfectly balancing nitrogen, oxygen, and carbon for life.',
    authorOrSource: 'Atmospheric Physics Institute'
  },

  // ── Stellar Physics & Quotes ──
  {
    id: 12,
    category: 'COSMIC_QUOTE',
    badge: '✨ Cosmic Wisdom',
    icon: 'quote',
    color: '#E879F9',
    title: 'The Stardust Connection',
    fact: '"The nitrogen in our DNA, the calcium in our teeth, the iron in our blood, the carbon in our apple pies were made in the interiors of collapsing stars. We are made of starstuff."',
    authorOrSource: 'Carl Sagan (Cosmos)'
  },
  {
    id: 13,
    category: 'COSMIC_QUOTE',
    badge: '✨ Cosmic Wisdom',
    icon: 'quote',
    color: '#60A5FA',
    title: 'The Beauty of the Cosmos',
    fact: '"Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious."',
    authorOrSource: 'Stephen Hawking'
  },
  {
    id: 14,
    category: 'STAR_PHYSICS',
    badge: '⚡ Stellar Physics',
    icon: 'star',
    color: '#F472B6',
    title: 'Gravitational Time Dilation',
    fact: 'According to Einstein\'s General Relativity, gravity bends both space and time. Clocks at sea level on Earth tick slightly slower than clocks on satellite orbits in space by roughly 45 microseconds every day, a difference GPS satellites must calibrate for.',
    authorOrSource: 'Albert Einstein / GPS Relativistic Physics'
  },
  {
    id: 15,
    category: 'COSMIC_QUOTE',
    badge: '✨ Cosmic Wisdom',
    icon: 'quote',
    color: '#FDBA74',
    title: 'Infinite Perspective',
    fact: '"Somewhere, something incredible is waiting to be known. The cosmos is within us. We are a way for the cosmos to know itself."',
    authorOrSource: 'Carl Sagan'
  }
];

export const CosmicQuotePopup: React.FC = () => {
  const [currentFact, setCurrentFact] = useState<CosmicFact>(() => {
    // Pick a random fact on every refresh / page load
    const randomIndex = Math.floor(Math.random() * COSMIC_FACTS.length);
    return COSMIC_FACTS[randomIndex];
  });

  const [isVisible, setIsVisible] = useState(true);
  const [isMinimized, setIsMinimized] = useState(false);

  // Trigger a new quote/fact every 10 minutes (600,000 ms)
  useEffect(() => {
    const interval = setInterval(() => {
      // Pick next or random fact
      setCurrentFact(prev => {
        let nextIndex = Math.floor(Math.random() * COSMIC_FACTS.length);
        if (COSMIC_FACTS[nextIndex].id === prev.id) {
          nextIndex = (nextIndex + 1) % COSMIC_FACTS.length;
        }
        return COSMIC_FACTS[nextIndex];
      });
      setIsVisible(true);
      setIsMinimized(false);
    }, 10 * 60 * 1000); // exactly 10 minutes

    return () => clearInterval(interval);
  }, []);

  const handleNextFact = () => {
    setCurrentFact(prev => {
      let nextIndex = Math.floor(Math.random() * COSMIC_FACTS.length);
      if (COSMIC_FACTS[nextIndex].id === prev.id) {
        nextIndex = (nextIndex + 1) % COSMIC_FACTS.length;
      }
      return COSMIC_FACTS[nextIndex];
    });
  };

  if (!isVisible) return null;

  if (isMinimized) {
    return (
      <div
        className="cosmic-popup-minimized"
        onClick={() => setIsMinimized(false)}
        title="Open Cosmic Wisdom & Galaxy Fact"
      >
        <span className="cosmic-mini-pulse" />
        <Sparkles size={14} color="#C4B5FD" />
        <span className="cosmic-mini-text">Cosmic Fact • {currentFact.badge}</span>
      </div>
    );
  }

  return (
    <div className="cosmic-popup-toast" role="alert">
      {/* Background Star Glow */}
      <div className="cosmic-popup-glow" style={{ background: `radial-gradient(circle, ${currentFact.color}33 0%, rgba(0,0,0,0) 70%)` }} />

      <div className="cosmic-popup-content">
        {/* Top Header Row */}
        <div className="cosmic-popup-header">
          <div className="cosmic-popup-badge" style={{ borderColor: `${currentFact.color}66`, color: currentFact.color }}>
            <Sparkles size={13} />
            <span>{currentFact.badge}</span>
          </div>

          <div className="cosmic-popup-controls">
            <button
              onClick={handleNextFact}
              className="cosmic-popup-icon-btn"
              title="Get another Galaxy / Planetary Fact"
            >
              <RefreshCw size={13} />
            </button>
            <button
              onClick={() => setIsMinimized(true)}
              className="cosmic-popup-icon-btn"
              title="Minimize to floating pill"
            >
              <Moon size={13} />
            </button>
            <button
              onClick={() => setIsVisible(false)}
              className="cosmic-popup-icon-btn close"
              title="Dismiss"
            >
              <X size={14} />
            </button>
          </div>
        </div>

        {/* Fact Title */}
        <h4 className="cosmic-popup-title" style={{ color: '#FFFFFF' }}>
          {currentFact.title}
        </h4>

        {/* Fact Body */}
        <p className="cosmic-popup-text">
          {currentFact.fact}
        </p>

        {/* Footer info / source */}
        <div className="cosmic-popup-footer">
          <span className="cosmic-popup-source">
            {currentFact.authorOrSource ? `✦ ${currentFact.authorOrSource}` : '✦ Verified Astrophysical Science'}
          </span>
          <span className="cosmic-timer-pill">Next update in 10m</span>
        </div>
      </div>
    </div>
  );
};

export default CosmicQuotePopup;
