import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Briefcase, Building2, CheckSquare, Plus, ShieldCheck, TrendingUp, Users } from 'lucide-react';
import { apiClient } from '../api/client';
import { useAuth } from '../context/AuthContext';
import { useCompanyResource } from '../hooks/useCompanyResource';
import { CompanyEmployeeApprovalQueue } from '../components/CompanyEmployeeApprovalQueue';
import { CompanyPayrollQueue } from '../components/CompanyPayrollQueue';
import { CompanyTagApprovalQueue } from '../components/CompanyTagApprovalQueue';
import { CompanyBadge, CompanyCard, CompanyDecision, CompanyDialog, CompanyState, CompanyTable, companyDate, companyMoney } from '../components/company/CompanyUi';
import { CompanyDirectory, CompanyInvitations, CompanyInviteDialog, CompanyRecruiters, CompanyReviews, CompanyTalent } from '../components/company/CompanyPeople';
import { CompanySettings, CompanySubscription } from '../components/company/CompanySettings';
import { companyHref, useCompanyNavigation, useCompanyWorkspace } from '../components/company/CompanyWorkspace';

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string | number; detail: string; icon: typeof Users }) {
  return <div className="cm-kpi"><div className="cm-kpi-label"><span>{label}</span><span className="cm-kpi-icon"><Icon size={18} /></span></div><strong className="cm-kpi-value">{value}</strong><small>{detail}</small></div>;
}

function CompanyOverview() {
  const resource = useCompanyWorkspace(); const { user } = useAuth(); const data = resource.data;
  const [invite, setInvite] = useState<'ROLE_HR' | 'ROLE_CANDIDATE' | null>(null);
  if (resource.loading || resource.error || !data) return <CompanyState loading={resource.loading} error={resource.error || (!resource.loading ? 'No company information was returned.' : '')} onRetry={resource.refresh} />;
  const decisions = [
    { label: 'Candidate verification', count: data.pendingVerifications, view: 'candidates', section: 'verifications' },
    { label: 'Employee onboarding', count: data.pendingOnboarding, view: 'employees', section: 'verifications' },
    { label: 'Salary authorization', count: data.pendingSalaries, view: 'payroll', section: 'disbursement' },
    { label: 'Separation requests', count: data.pendingTerminations, view: 'employees', section: 'terminations' },
  ];
  return <div className="cm-stack"><section className="cm-welcome"><div><span className="cm-eyebrow">YOUR COMPANY, AT A GLANCE</span><h2>Welcome back, {user?.firstName || 'Manager'}.</h2><p>Here’s what’s happening at {data.companyName}. Keep your team moving with clear priorities and informed decisions.</p></div><div className="cm-actions"><button className="cm-button cm-button-primary" onClick={() => setInvite('ROLE_HR')}><Plus size={15} /> Invite recruiter</button><button className="cm-button" onClick={() => setInvite('ROLE_CANDIDATE')}>Invite candidate</button></div></section>
  <div className="cm-kpis"><Metric label="Company employees" value={data.totalEmployees} detail={`${data.activeEmployees} currently active`} icon={Users} /><Metric label="Open jobs" value={data.activeJobsCount} detail="Published, active openings" icon={Briefcase} /><Metric label="HR recruiters" value={data.totalHrMembers} detail={`${data.verifiedHrMembers} company-verified`} icon={ShieldCheck} /><Metric label="Pending decisions" value={data.pendingApprovalsCount} detail="Across company approval queues" icon={CheckSquare} /></div>
  <div className="cm-grid-wide"><CompanyCard title="Needs your attention" description="Review pending work in its dedicated approval queue." action={<span className="cm-badge cm-badge-warning">{data.pendingApprovalsCount} pending</span>}><div className="cm-list">{decisions.map(item => <Link className="cm-list-row" to={companyHref(item.view, item.section)} key={item.view + item.section}><div><strong>{item.label}</strong><small>{item.count === 0 ? 'Nothing awaiting review' : `${item.count} awaiting review`}</small></div><div className="cm-actions"><CompanyBadge value={String(item.count)} /><ArrowUpRight size={17} /></div></Link>)}</div></CompanyCard>
  <CompanyCard title="Company snapshot" action={<Link className="cm-button" to={companyHref('profile')}>View profile</Link>}><dl className="cm-details"><div><dt>Company</dt><dd>{data.companyName}</dd></div><div><dt>Verification</dt><dd><CompanyBadge value={data.isVerified} /></dd></div><div><dt>Industry</dt><dd>{data.industry || 'Not recorded'}</dd></div><div><dt>Location</dt><dd>{data.location || 'Not recorded'}</dd></div></dl><div className="cm-list-row" style={{ marginTop: 24 }}><div><strong>Team goals</strong><small>{data.completedTasks} of {data.totalTasks} completed</small></div><Link className="cm-button" to={companyHref('strategy')}>View goals</Link></div></CompanyCard></div>
  <CompanyCard title="Explore company reports" description="Workforce, hiring, payroll and performance — based on recorded activity." action={<Link className="cm-button" to={companyHref('analytics')}><TrendingUp size={16} /> Open reports</Link>}><p className="cm-prose" style={{ marginBottom: 0 }}>Your overview uses current company records. Missing information is shown clearly instead of being replaced with sample figures.</p></CompanyCard>
  {invite && <CompanyInviteDialog role={invite} onClose={() => setInvite(null)} onSuccess={resource.refresh} />}</div>;
}

function safeWebAddress(value?: string) { try { const url = new URL(value || ''); return ['http:', 'https:'].includes(url.protocol) ? url.href : undefined; } catch { return undefined; } }
function safeImageAddress(value?: string) { return value?.startsWith('/') && !value.startsWith('//') ? value : safeWebAddress(value); }

function CompanyProfileEditor({ onClose }: { onClose: () => void }) {
  const resource = useCompanyWorkspace(); const data = resource.data!;
  const [form, setForm] = useState({ name: data.companyName || '', tagline: data.tagline || '', industry: data.industry || '', companySize: data.companySize || '', website: data.website || '', location: data.location || '', phone: data.phone || '', description: data.description || '', logoUrl: data.logoUrl || '', bannerUrl: data.bannerUrl || '' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const fields = [['name', 'Company name', 200], ['tagline', 'Tagline', 255], ['industry', 'Industry', 100], ['companySize', 'Company size', 30], ['website', 'Website', 500], ['location', 'Location', 200], ['phone', 'Contact phone', 20], ['logoUrl', 'Logo image URL', 500], ['bannerUrl', 'Banner image URL', 500]] as const;
  return <CompanyDialog title="Edit company profile" onClose={() => { if (!busy) onClose(); }}><form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await apiClient.put('/admin/company/profile', form); resource.refresh(); onClose(); } catch (err: any) { setError(err?.response?.data?.message || 'Company profile could not be saved.'); } finally { setBusy(false); } }}><div className="cm-grid">{fields.map(([key, label, length]) => <label className="cm-field" key={key}>{label}{key === 'name' ? ' *' : ''}<input required={key === 'name'} type={key === 'website' ? 'url' : key === 'phone' ? 'tel' : 'text'} maxLength={length} value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} />{key.endsWith('Url') && <small>Use an existing image URL or a local application path.</small>}</label>)}</div><label className="cm-field">About your company<textarea maxLength={10000} rows={4} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label>{error && <p role="alert" className="cm-error-text">{error}</p>}<footer className="cm-actions cm-form-actions"><button className="cm-button" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="cm-button cm-button-primary" disabled={busy || !form.name.trim()}>{busy ? 'Saving…' : 'Save company profile'}</button></footer></form></CompanyDialog>;
}

function CompanyProfile({ section }: { section: string }) {
  const resource = useCompanyWorkspace(); const data = resource.data; const [editing, setEditing] = useState(false);
  if (section === 'subscription') return <CompanySubscription />;
  if (resource.loading || !data) return <CompanyState loading={resource.loading} error={resource.error} onRetry={resource.refresh} />;
  return <div className="cm-stack"><CompanyCard title={section === 'contact' ? 'Contact & location' : section === 'branding' ? 'Brand identity' : section === 'verification' ? 'Company verification' : data.companyName} description={section === 'overview' ? data.tagline || 'Company overview and public information.' : undefined} action={section !== 'verification' && <button className="cm-button" onClick={() => setEditing(true)}>Edit profile</button>}>
    {section === 'verification' ? <div className="cm-stack"><div className="cm-actions"><ShieldCheck size={28} /><CompanyBadge value={data.isVerified} /></div><p className="cm-prose">{data.isVerified ? 'Your company is marked as verified in the platform’s company record.' : 'Your company is not currently marked as verified. Contact the platform team to review your company verification.'}</p><dl className="cm-details"><div><dt>Company ID</dt><dd>{data.companyId}</dd></div><div><dt>Workspace identifier</dt><dd>{data.companySlug}</dd></div></dl></div> : section === 'branding' ? <div className="cm-grid">{[['Logo', data.logoUrl], ['Banner', data.bannerUrl]].map(([label, url]) => <div key={label}><h3>{label}</h3>{safeImageAddress(url) ? <img className="cm-brand-preview" src={safeImageAddress(url)} alt={`${data.companyName} ${label?.toLowerCase()}`} loading="lazy" decoding="async" /> : <div className="cm-state"><Building2 size={32} /><p>No {label?.toLowerCase()} recorded.</p></div>}</div>)}</div> : <><dl className="cm-details">{(section === 'contact' ? [['Company email', data.email], ['Phone', data.phone], ['Location', data.location], ['Website', data.website]] : [['Company name', data.companyName], ['Industry', data.industry], ['Company size', data.companySize], ['Founded', data.foundedYear], ['Website', data.website], ['Workspace identifier', data.companySlug]]).map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd>{label === 'Website' && safeWebAddress(String(value || '')) ? <a href={safeWebAddress(String(value))} target="_blank" rel="noopener noreferrer">{value} ↗</a> : value || 'Not recorded'}</dd></div>)}</dl>{section === 'overview' && <div style={{ marginTop: 28 }}><h3>About the company</h3><p className="cm-prose">{data.description || 'No company description has been added yet.'}</p></div>}</>}
  </CompanyCard>{editing && <CompanyProfileEditor onClose={() => setEditing(false)} />}</div>;
}

interface PerformanceStats { totalReviews: number; averageRating: number; excellentCount: number; goodCount: number; averageCount: number; needsImprovementCount: number; departmentRatings: Array<{ department: string; averageScore: number; count: number }> }
interface CompanyAnalytics { totalHires: number; activeEmployees: number; activeJobsCount: number; hiringByDepartment: Array<{ department: string; hires: number; percentage: number }>; monthlyStats: Array<{ month: string; hired: number }>; employeeStatuses: Array<{ status: string; count: number }>; payrollByCurrency: Array<{ currency: string; status: string; count: number; amount: number }> }
function CompanyBars({ rows, max }: { rows: Array<{ label: string; value: number }>; max?: number }) {
  const maximum = max || Math.max(1, ...rows.map(row => row.value));
  return <div>{rows.length ? rows.map(row => <div className="cm-bar-row" key={row.label}><span>{row.label}</span><div className="cm-bar-track" aria-hidden="true"><span style={{ width: `${Math.max(0, Math.min(100, row.value / maximum * 100))}%` }} /></div><strong>{row.value.toLocaleString()}</strong></div>) : <CompanyState empty="No recorded activity yet" />}</div>;
}
function CompanyAnalyticsView({ section }: { section: string }) {
  const analytics = useCompanyResource<CompanyAnalytics>(section === 'performance' ? null : '/admin/company/analytics');
  const performance = useCompanyResource<PerformanceStats>(section === 'performance' ? '/admin/company/performance/stats' : null);
  const resource = section === 'performance' ? performance : analytics;
  if (resource.loading || resource.error) return <CompanyState loading={resource.loading} error={resource.error} onRetry={resource.refresh} />;
  if (section === 'performance') {
    const data = performance.data;
    return <div className="cm-stack"><div className="cm-kpis"><Metric label="Recorded reviews" value={data?.totalReviews ?? 0} detail="All review periods" icon={CheckSquare} /><Metric label="Average rating" value={data?.totalReviews ? `${data.averageRating.toFixed(2)} / 5` : '—'} detail="From recorded reviews" icon={TrendingUp} /><Metric label="Excellent reviews" value={data?.excellentCount ?? 0} detail="Recorded category" icon={ShieldCheck} /><Metric label="Needs improvement" value={data?.needsImprovementCount ?? 0} detail="Recorded category" icon={Users} /></div><CompanyCard title="Average rating by department" description="Aggregate of recorded review ratings on a 1–5 scale."><CompanyBars max={5} rows={(data?.departmentRatings || []).map(row => ({ label: `${row.department} (${row.count})`, value: row.averageScore }))} /></CompanyCard></div>;
  }
  const data = analytics.data;
  if (!data) return <CompanyState empty="No report data available" />;
  return <div className="cm-stack">{section === 'payroll' ? <CompanyCard title="Payroll by currency and status" description="Recorded disbursements are grouped by currency; unlike currencies are never added together.">{data.payrollByCurrency.length ? <CompanyTable label="Payroll totals by currency and status" headings={['Currency', 'Status', 'Records', 'Amount']}>{data.payrollByCurrency.map(row => <tr key={`${row.currency}-${row.status}`}><td>{row.currency}</td><td><CompanyBadge value={row.status} /></td><td>{row.count}</td><td>{companyMoney(row.amount, row.currency)}</td></tr>)}</CompanyTable> : <CompanyState empty="No payroll records yet" />}</CompanyCard> : <><div className="cm-kpis"><Metric label="Employee records" value={data.totalHires} detail="All company employment records" icon={Users} /><Metric label="Active workforce" value={data.activeEmployees} detail="Currently active employees" icon={Briefcase} /><Metric label="Open jobs" value={data.activeJobsCount} detail="Currently active job postings" icon={TrendingUp} /><Metric label="Departments" value={data.hiringByDepartment.length} detail="Including unassigned records" icon={Building2} /></div><div className="cm-grid"><CompanyCard title={section === 'employees' ? 'Employment status' : 'Monthly onboarding'} description={section === 'employees' ? 'Current status distribution across employee records.' : 'Employee records created each month, not application or offer counts.'}><CompanyBars rows={section === 'employees' ? data.employeeStatuses.map(row => ({ label: row.status.replaceAll('_', ' '), value: row.count })) : data.monthlyStats.map(row => ({ label: row.month, value: row.hired }))} /></CompanyCard><CompanyCard title="Workforce by department" description="All company employee records grouped by department."><CompanyBars rows={data.hiringByDepartment.map(row => ({ label: row.department, value: row.hires }))} /></CompanyCard></div></>}<p className="cm-notice">Time-to-hire, retention benchmarks and cost-per-hire are not shown because this application does not record reliable aggregates for those measures.</p></div>;
}

interface CompanyTask { id: number; title: string; description?: string; status: string; priority: string; assignedToName: string; dueDate?: string; createdAt: string }
function CompanyTaskDialog({ onClose, onSuccess }: { onClose: () => void; onSuccess: () => void }) {
  const recruiters = useCompanyResource<Array<{ userId: number; name: string; active: boolean; companyVerified: boolean }>>('/company/verifications/hrs');
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [assignee, setAssignee] = useState(''); const [dueDate, setDueDate] = useState(''); const [priority, setPriority] = useState('MEDIUM'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <CompanyDialog title="New team goal" onClose={() => { if (!busy) onClose(); }}><form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await apiClient.post('/company/tasks', { title: title.trim(), description: description.trim(), assignedToUserId: assignee ? Number(assignee) : null, dueDate: dueDate ? new Date(`${dueDate}T23:59:59`).toISOString() : null, priority, category: 'GENERAL' }); onSuccess(); onClose(); } catch (err: any) { setError(err?.response?.data?.message || 'The goal could not be saved.'); } finally { setBusy(false); } }}><label className="cm-field">Goal title *<input required maxLength={255} value={title} onChange={e => setTitle(e.target.value)} placeholder="Describe a clear team goal" /></label><label className="cm-field">Description<textarea maxLength={5000} rows={3} value={description} onChange={e => setDescription(e.target.value)} /></label><label className="cm-field">Assign to<select value={assignee} onChange={e => setAssignee(e.target.value)}><option value="">Unassigned</option>{recruiters.data?.filter(person => person.active && person.userId).map(person => <option key={person.userId} value={person.userId}>{person.name}</option>)}</select></label>{recruiters.error && <p className="cm-notice">Recruiter list unavailable. You can create an unassigned goal.</p>}<div className="cm-grid"><label className="cm-field">Due date<input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} /></label><label className="cm-field">Priority<select value={priority} onChange={e => setPriority(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label></div>{error && <p role="alert" className="cm-error-text">{error}</p>}<footer className="cm-actions cm-form-actions"><button className="cm-button" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="cm-button cm-button-primary" disabled={busy || !title.trim()}>{busy ? 'Creating…' : 'Create goal'}</button></footer></form></CompanyDialog>;
}

function CompanyStrategy({ section }: { section: string }) {
  const resource = useCompanyResource<CompanyTask[]>(section === 'copilot' ? null : '/company/tasks'); const workspace = useCompanyWorkspace();
  const [status, setStatus] = useState('ALL'); const [open, setOpen] = useState(false); const [decision, setDecision] = useState<{ task: CompanyTask; status: string } | null>(null);
  if (section === 'copilot') return <CompanyCard title="Current strategy summary" description="A factual summary of the same live company records used in your overview.">{workspace.loading || !workspace.data ? <CompanyState loading={workspace.loading} error={workspace.error} onRetry={workspace.refresh} /> : <div className="cm-stack"><p className="cm-prose">{workspace.data.companyName} has {workspace.data.activeEmployees} active employees, {workspace.data.totalHrMembers} HR recruiters and {workspace.data.activeJobsCount} open jobs. There are {workspace.data.pendingApprovalsCount} pending company decisions. Your team has completed {workspace.data.completedTasks} of {workspace.data.totalTasks} recorded goals.</p><div className="cm-actions"><Link className="cm-button cm-button-primary" to={companyHref('dashboard')}>Review pending decisions</Link><Link className="cm-button" to={companyHref('strategy', 'tasks')}>Open team goals</Link></div><p className="cm-notice">The previous strategy copilot used canned responses, not company analysis. This summary uses actual records; the existing AI Guide remains available for product guidance.</p></div>}</CompanyCard>;
  const tasks = (resource.data || []).filter(task => status === 'ALL' || task.status === status);
  return <CompanyCard title="Team goals" description="Company tasks, ownership and progress." action={<button className="cm-button cm-button-primary" onClick={() => setOpen(true)}><Plus size={15} /> New goal</button>}><div className="cm-toolbar"><label className="cm-field">Status<select value={status} onChange={e => setStatus(e.target.value)}><option value="ALL">All goals</option><option>TODO</option><option>IN_PROGRESS</option><option>COMPLETED</option></select></label><button className="cm-button" onClick={resource.refresh}>Refresh</button></div>{resource.loading || resource.error || !tasks.length ? <CompanyState loading={resource.loading} error={resource.error} empty="No matching team goals" onRetry={resource.refresh} /> : <div className="cm-list">{tasks.map(task => <div className="cm-list-row" key={task.id}><div><strong>{task.title}</strong><small>{task.assignedToName || 'Unassigned'} · Due {companyDate(task.dueDate)}</small>{task.description && <p className="cm-prose">{task.description}</p>}<CompanyBadge value={task.status} /></div><div className="cm-actions"><button className="cm-button" onClick={() => setDecision({ task, status: task.status === 'COMPLETED' ? 'TODO' : task.status === 'TODO' ? 'IN_PROGRESS' : 'COMPLETED' })}>{task.status === 'COMPLETED' ? 'Reopen' : task.status === 'TODO' ? 'Start goal' : 'Complete'}</button></div></div>)}</div>}{open && <CompanyTaskDialog onClose={() => setOpen(false)} onSuccess={() => { resource.refresh(); workspace.refresh(); }} />}{decision && <CompanyDecision title="Update goal status?" description={`${decision.task.title} will be marked ${decision.status.replaceAll('_', ' ').toLowerCase()}.`} confirmLabel="Update goal" onClose={() => setDecision(null)} onConfirm={async () => { await apiClient.put(`/company/tasks/${decision.task.id}/status`, { status: decision.status }); resource.refresh(); workspace.refresh(); }} />}</CompanyCard>;
}

export default function CompanyManagerDashboard() {
  const { item, section } = useCompanyNavigation();
  if (item.id === 'profile') return <CompanyProfile section={section} />;
  if (item.id === 'recruiters') return section === 'invitations' ? <CompanyInvitations role="ROLE_HR" /> : section === 'approvals' ? <CompanyTagApprovalQueue initialTab="HR_TEAM" /> : <CompanyRecruiters />;
  if (item.id === 'candidates') return section === 'invitations' ? <CompanyInvitations role="ROLE_CANDIDATE" /> : section === 'verifications' ? <CompanyTagApprovalQueue initialTab="CANDIDATES" /> : <CompanyTalent />;
  if (item.id === 'employees') return section === 'performance' ? <CompanyReviews /> : section === 'terminations' || section === 'verifications' ? <CompanyEmployeeApprovalQueue initialSubTab={section === 'terminations' ? 'TERMINATIONS' : 'VERIFICATIONS'} /> : <CompanyDirectory />;
  if (item.id === 'payroll') return <CompanyPayrollQueue initialFilter={section === 'history' ? 'ALL' : 'PENDING'} />;
  if (item.id === 'analytics') return <CompanyAnalyticsView section={section} />;
  if (item.id === 'settings') return <CompanySettings section={section} />;
  if (item.id === 'strategy') return <CompanyStrategy section={section} />;
  if (item.id === 'chat') return <CompanyCard title="Team collaboration"><Link className="cm-button cm-button-primary" to="/team-chat">Open team chat</Link></CompanyCard>;
  return <CompanyOverview />;
}
