package com.talentiq.common.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    JOB_RECOMMENDATION,
    NEW_JOB_POSTED,
    RESUME_PARSED,
    MESSAGE_RECEIVED,
    PROFILE_VIEWED,
    INTERVIEW_SCHEDULED,
    OFFER_RECEIVED,
    SYSTEM_ANNOUNCEMENT
}
